import test from 'node:test'
import assert from 'node:assert/strict'
import {extractEditorialMetadata,metadataEntry,createInventory,verifyInventory,inventoryHash,comparisonSet,reviewCandidate,verifyCandidateReceipt} from '../scripts/lib/mwf-inventory.mjs'
import {issueTopicAdoption} from '../src/lib/tieredPublication.mjs'
import {prepareMetadataInventory} from '../scripts/mwf-inventory-metadata.mjs'
const secret='synthetic-only',path='content/posts/2026-09-14-old.md'
const raw=Buffer.from('---\ntitle: "Old"\nexcerpt: "Public summary"\ncategory: "その他"\nprivate_request: "DO_NOT_EXPORT"\n---\nDO_NOT_PARSE_BODY')
const head={url:'https://aisoukai-media.vercel.app/blog/2026-09-14-old',title:'Old',description:'Public summary'}
function input(){const blob=inventoryHash(raw),preservation={schema:1,reconciled:false,entries:[{path,blob}]},reconciliation={schema:1,reconciled:false,canonicalRevision:'a'.repeat(40),entries:[{path,blob,canonicalBlob:blob}],unidentifiedTopics:[path],usedTopicIds:[]};return{preservation,reconciliation,preservationBytes:Buffer.from(JSON.stringify(preservation)),reconciliationBytes:Buffer.from(JSON.stringify(reconciliation)),entries:[metadataEntry({path,raw,source:'canonical',quarantine:true,head})],secret}}
test('only allowlisted scalar metadata is extracted; private fields/body never enter result',()=>{assert.deepEqual(extractEditorialMetadata(raw),{title:'Old',excerpt:'Public summary',category:'その他'});assert.equal(JSON.stringify(input().entries).includes('DO_NOT'),false);for(const prefix of ['private_request: "','very_long_private_request_key_over_32: "','private_request: ['])assert.equal(extractEditorialMetadata(Buffer.from(`---\n${prefix}\ntitle: private\nexcerpt: private\ncategory: private\n"\n---`)),null)})
test('complete separate schema2 evidence retains unresolved quarantine and rejects unsigned use/missing originals',()=>{const i=input(),signed=createInventory(i);assert.deepEqual(verifyInventory(signed,secret).quarantine,[path]);assert.equal(verifyInventory(createInventory({...i,prepareOnly:true}),secret),null);assert.throws(()=>createInventory({...i,entries:[]}),/incomplete/);assert.equal(metadataEntry({path,raw,source:'canonical',quarantine:true,head:{...head,title:'Wrong'}}).metadata,null)})
test('prepare-only binds actual public head fields to fixed revision without signing or approving',async()=>{const i=input();let calls=0;const result=await prepareMetadataInventory({...i,readLocal:async()=>raw,github:async(p,revision)=>{assert.equal(revision,'a'.repeat(40));return p==='content/posts'?[{path,type:'file'}]:raw},readHead:async()=>{calls++;return head}});assert.equal(result.unsigned,true);assert.equal(calls,1);assert.equal(result.payload.entries.length,1)})
test('independent candidate evidence covers quarantine/local records and invalidates after topic or comparison changes',async()=>{const topic={id:'new',title:'Different',status:'approved'},adoption=issueTopicAdoption(topic,secret);const set=comparisonSet([...input().entries,metadataEntry({path:'content/posts/2026-09-14-local.md',raw:Buffer.from(raw.toString().replace('Old','Local')),source:'local'})]);let calls=0;const request=async(_url,options)=>{calls++;const body=JSON.parse(options.body);assert.equal(JSON.stringify(body).includes('DO_NOT'),false);assert.equal(JSON.parse(body.messages[1].content).comparisons.length,2);return{ok:true,json:async()=>({id:'independent-1',choices:[{finish_reason:'stop',message:{content:'{"decision":"clear"}'}}]})}};const result=await reviewCandidate({topic,set,adoption,request,secret});assert.equal(result.status,'clear');assert.equal(calls,1);assert.equal(verifyCandidateReceipt(result.receipt,topic,set,secret),true);assert.equal(verifyCandidateReceipt(result.receipt,{...topic,title:'Changed'},set,secret),false);assert.equal(verifyCandidateReceipt(result.receipt,topic,comparisonSet([]),secret),false)})
test('missing adoption, incomplete comparison or related/ambiguous decisions never clear',async()=>{const topic={id:'new',title:'Different',status:'approved'},set=comparisonSet(input().entries),adoption=issueTopicAdoption(topic,secret);let calls=0;const request=async()=>{calls++;return{ok:true,json:async()=>({id:'independent',choices:[{finish_reason:'stop',message:{content:'{"decision":"related"}'}}]})}};assert.equal((await reviewCandidate({topic,set,request,secret})).status,'hold');assert.equal(calls,0);assert.equal((await reviewCandidate({topic,set:comparisonSet([{metadata:null}]),adoption,request,secret})).reason,'comparison_metadata_incomplete');assert.equal((await reviewCandidate({topic,set,adoption,request,secret})).reason,'related')})

test('ordinary single-line empty tags and balanced unknown flow values are safely skipped',()=>{const value=Buffer.from(raw.toString().replace('---\n','---\ntags: []\nunknown: {x: ["private", "opaque"]}\n'));assert.equal(extractEditorialMetadata(value).title,'Old');assert.equal(JSON.stringify(extractEditorialMetadata(value)).includes('opaque'),false)})

test('private sequence quoted scalar and quoted-key continuation cannot masquerade as public metadata',()=>{for(const prefix of ['private_request:\n  - "','"private:request": "']){const value=Buffer.from(`---\n${prefix}\ntitle: Synthetic private\nexcerpt: Synthetic private\ncategory: Synthetic private\n"\n---`);assert.equal(extractEditorialMetadata(value),null)}})

test('private sequence and quoted-key multiline flow mappings never expose their nested fields',()=>{for(const prefix of ['private_request:\n  - {','"private:request": {'])assert.equal(extractEditorialMetadata(Buffer.from(`---\n${prefix}\ntitle: Synthetic private,\nexcerpt: Synthetic private,\ncategory: Synthetic private\n}\n---`)),null)})

test('opaque private/body bytes are never UTF8-decoded, including all continuation regressions',()=>{
 const sentinel=Buffer.from('PRIVATE_DECODE_SENTINEL'),body=Buffer.from('BODY_DECODE_SENTINEL')
 const samples=[Buffer.from('---\ntitle: Public\nexcerpt: Public\ncategory: その他\nprivate_request: "PRIVATE_DECODE_SENTINEL"\n---\nBODY_DECODE_SENTINEL'),...['private_request: "','private_request:\n  - "','"private:request": "','private_request:\n  - {','"private:request": {'].map(prefix=>Buffer.from(`---\n${prefix}\ntitle: PRIVATE_DECODE_SENTINEL\nexcerpt: PRIVATE_DECODE_SENTINEL\ncategory: PRIVATE_DECODE_SENTINEL\n"\n}\n---\nBODY_DECODE_SENTINEL`))]
 const original=Buffer.prototype.toString;let violations=0
 Buffer.prototype.toString=function(encoding,...args){if((encoding===undefined||/^utf-?8$/i.test(encoding))&&(this.includes(sentinel)||this.includes(body)))violations++;return original.call(this,encoding,...args)}
 try{for(const value of samples){extractEditorialMetadata(value);inventoryHash(value)}assert.equal(violations,0)}finally{Buffer.prototype.toString=original}
})
