import test from 'node:test'
import assert from 'node:assert/strict'
import {readFileSync} from 'node:fs'
import ts from 'typescript'
import {isPreservedUnreviewedDraft} from '../scripts/lib/mwf-restoration.mjs'
import {approvedComparisonUpdates} from '../scripts/lib/mwf-human-comparisons.mjs'
import * as authority from '../src/lib/mwfServerAuthority.mjs'
import * as inventory from '../scripts/lib/mwf-inventory.mjs'
import * as tiered from '../src/lib/tieredPublication.mjs'
import {parseCsv} from '../scripts/csv-parser.mjs'
const secret='synthetic-only'
function load(source,modules,env){const exports={};new Function('require','exports','process',ts.transpileModule(readFileSync(source,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText)(name=>{if(!(name in modules))throw Error(`unexpected import ${name}`);return modules[name]},exports,{env,cwd:()=>'/synthetic'});return exports}
test('authenticated monthly finalization atomically saves nine signed adoptions and repeat needs no new adoption',async()=>{
 let csv='id,discovered_at,source_type,source_url,topic,title_candidate,category,target_keyword,patient_intent,priority,medical_risk,status,publish_date,notes\n',writes=0,authenticated=0;const topics=Array.from({length:9},(_,i)=>({id:`2026-09-topic-${String(i+1).padStart(3,'0')}`,status:'selected',title:`Synthetic ${i}`,category:'その他',medicalRisk:'low'}))
 const modules={'fs':{},'path':{},'next/cache':{revalidatePath(){}},'@/lib/adminAuth':{requireAdmin:async()=>{authenticated++}},'@/lib/monthlyTopicCandidates':{getTopicCandidatePath:()=> 'data/topic-candidates/synthetic.json'},'@/lib/tieredPublication.mjs':{issueTopicAdoption:row=>tiered.issueTopicAdoption(row,secret)},'@/lib/githubContents':{readGitHubBranchHead:async()=> 'a'.repeat(40),readGitHubFile:async path=>({content:path.includes('human-approvals')?JSON.stringify(approval):path.includes('claims')?JSON.stringify(tiered.signBlogEvidence('mwf-server-claim',{comparisonEntries:recorded},secret)):path.includes('article-topics')?csv:JSON.stringify({month:'2026-09',targetPostCount:9,topics})}),commitGitHubFiles:async(_message,files,options)=>{writes++;assert.equal(options.expectedHeadSha,'a'.repeat(40));assert.equal(authenticated,1);assert.equal(files.length,10);csv=files[0].content;for(const row of parseCsv(csv)){const proof=tiered.verifyBlogEvidence(JSON.parse(files.find(f=>f.path===`data/topic-adoptions/${row.id}.json`).content),'teacher-topic-adoption',secret);assert.equal(proof.topicVersion,tiered.topicContentVersion(row));assert.equal(proof.topicId,row.id)}return{sha:'b'.repeat(40)}}}}
 const actions=load('src/app/admin/topic-candidates/actions.ts',modules,{GITHUB_REVIEW_TOKEN:'synthetic'})
 assert.equal((await actions.finalizeSelectedTopicCandidatesAction('2026-09')).ok,true)
 assert.equal((await actions.finalizeSelectedTopicCandidatesAction('2026-09')).ok,true);assert.equal(writes,1);assert.equal(authenticated,2)
})
function runtime(){
 const localRaw=Buffer.from('---\ntitle: Synthetic 4\nexcerpt: Synthetic excerpt\ncategory: その他\ndate: 2026-08-01\ndraft: true\nreviewed: false\nauto_approved: false\npublication_status: draft\n---\nSynthetic body')
 const entries=Array.from({length:54},(_,i)=>({path:`content/posts/2026-08-01-synthetic-${i}.md`,source:i<8?'local':'canonical',gitBlob:String(i%10).repeat(40),blob:String(i%10).repeat(64),quarantine:i<4,metadata:{title:`Synthetic ${i}`,excerpt:'Synthetic excerpt',category:'その他'}}));entries[4]={...inventory.metadataEntry({path:entries[4].path,raw:localRaw,source:'local'}),quarantine:false};const bytes=Buffer.from(JSON.stringify({payload:{schema:2,entries,quarantine:entries.slice(0,4).map(e=>e.path),preservationHash:'a'.repeat(64),reconciliationHash:'b'.repeat(64)}}));let captured,bodyReads=0,unknown=false,recorded=[],approvedRaw,approval,approvedPath=entries[10].path,restored=false
 const topic={id:'synthetic',title_candidate:'New synthetic',status:'approved'}
 const modules={'../../scripts/lib/mwf-restoration.mjs':{isPreservedUnreviewedDraft},'../../scripts/lib/mwf-human-comparisons.mjs':{approvedComparisonUpdates},'./mwfArticleSerialization.mjs':{},'node:fs/promises':{readFile:async()=>localRaw},'node:path':{join:(...parts)=>parts.join('/')},'gray-matter':{},'./githubContents':{readGitHubFile:async path=>({content:path.includes('human-approvals')?JSON.stringify(approval):path.includes('claims')?JSON.stringify(tiered.signBlogEvidence('mwf-server-claim',{comparisonEntries:recorded},secret)):path.includes('article-topics')?'id,title_candidate,status\nsynthetic,New synthetic,approved\n':JSON.stringify(tiered.issueTopicAdoption(topic,secret))}),readGitHubBytes:async path=>{if(path.startsWith('data/mwf/inventories/'))return{bytes};bodyReads++;if(approvedRaw&&path===approvedPath)return{bytes:approvedRaw};if(restored&&path===entries[4].path)return{bytes:localRaw};throw Error('body read forbidden')},readGitHubDirectory:async path=>path==='content/posts'?[...entries.filter(e=>e.source==='canonical'||restored&&e.path===entries[4].path).map(e=>({type:'file',path:e.path,sha:approvedRaw&&e.path===approvedPath?inventory.artifactGitBlob(approvedRaw):recorded.find(r=>r.path===e.path)?.gitBlob??e.gitBlob})),...(unknown?[{type:'file',path:'content/posts/2026-08-01-unknown.md',sha:'f'.repeat(40)}]:[])]:path==='data/mwf/human-approvals'?(approval?[{type:'file',path:`data/mwf/human-approvals/${approval.payload.rawVersion}.json`}]:[]):recorded.length?[{type:'file',path:`data/mwf/claims/${'a'.repeat(64)}.json`}]:[]},'./mwfServerAuthority.mjs':{...authority,MWF_INVENTORY_ANCHOR:authority.serverHash(bytes),createServerAuthority:options=>{captured=options;return{}}},'./tieredPublication.mjs':tiered,'./dmpArticleState.mjs':{},'./posts':{},'../../scripts/csv-parser.mjs':{parseCsv},'../../scripts/lib/mwf-inventory.mjs':inventory,'./mwfMinorAuthority.mjs':{},'../../scripts/lib/mwf-tiered-review.mjs':{}}
 load('src/lib/mwfServerRuntime.ts',modules,{ADMIN_REVIEW_COOKIE_SECRET:secret,GITHUB_REVIEW_TOKEN:'synthetic'}).createMwfServerRuntime()
 return{validate:()=>captured.validate({operation:'prepare',topicId:topic.id,topicVersion:tiered.topicContentVersion(topic),artifactPath:null},'a'.repeat(40)),bodyReads:()=>bodyReads,restore:async()=>{restored=true;const request={schema:4,operation:'restore-reflect',artifactPath:entries[4].path,artifactBlob:entries[4].blob};const validated=await captured.validate(request,'a'.repeat(40));assert.equal(validated.ok,true);recorded=captured.recordArtifacts(request,validated,[]);return captured.reflect(request,{status:'draft-review-required'},'a'.repeat(40))},approveLocal:()=>{approvedPath=entries[4].path;approvedRaw=Buffer.from(localRaw.toString().replace('reviewed: false','reviewed: true'));approval=tiered.signBlogEvidence('human-approved-baseline',{path:approvedPath,rawVersion:authority.serverHash(approvedRaw),contentVersion:'a'.repeat(64),humanAction:'authenticated_admin_approve',reviewedBy:'Synthetic',reviewedAt:'2026-09-19T01:00:00Z'},secret)},approve:()=>{approvedRaw=Buffer.from('---\ntitle: Synthetic 10\nexcerpt: Synthetic excerpt\ncategory: その他\nreviewed: true\n---\nSynthetic body');approval=tiered.signBlogEvidence('human-approved-baseline',{path:entries[10].path,rawVersion:authority.serverHash(approvedRaw),contentVersion:'a'.repeat(64),humanAction:'authenticated_admin_approve',reviewedBy:'Synthetic',reviewedAt:'2026-09-19T01:00:00Z'},secret)},record:(kind)=>{const path=entries[10].path,raw='---\ntitle: Updated synthetic\nexcerpt: Updated synthetic excerpt\ncategory: その他\n---\nSynthetic body';recorded=captured.recordArtifacts({artifactPath:path},{ok:true,kind,...(kind==='normal'?{validatedBytes:Buffer.from(raw)}:{})},kind==='minor'?[{path,content:raw}]:[]);assert.equal(recorded.length,1)},setUnknown:()=>{unknown=true}}
}
test('server compares anchored and listing metadata without historical body reads, unknown changes fail closed',async()=>{const f=runtime();assert.equal((await f.validate()).ok,true);assert.equal(f.bodyReads(),0);f.setUnknown();assert.equal((await f.validate()).ok,false);assert.equal(f.bodyReads(),0)})

test('signed metadata for exact normal draft and minor revision permits subsequent preparation without body reads',async()=>{for(const kind of ['normal','minor']){const f=runtime();f.record(kind);assert.equal((await f.validate()).ok,true);assert.equal(f.bodyReads(),0)}})

test('actual server prepare accepts known Human-approved revision through authenticated exact-byte metadata',async()=>{const f=runtime();f.approve();assert.equal((await f.validate()).ok,true);assert.equal(f.bodyReads(),1)})

test('restored exact local bytes reflect opaquely and signed canonical provenance survives later Human approval',async()=>{const f=runtime(),proof=await f.restore();assert.equal(proof.source,'production-restore');assert.equal(proof.published,false);assert.equal(proof.contentVersion,undefined);assert.equal(proof.artifactVersion,proof.blob);f.approveLocal();assert.equal((await f.validate()).ok,true)})
