import test from 'node:test'
import assert from 'node:assert/strict'
import {readFileSync} from 'node:fs'
import ts from 'typescript'
import * as authority from '../src/lib/mwfServerAuthority.mjs'
import * as inventory from '../scripts/lib/mwf-inventory.mjs'
import * as tiered from '../src/lib/tieredPublication.mjs'
import {parseCsv} from '../scripts/csv-parser.mjs'
const secret='synthetic-only'
function load(source,modules,env){const exports={};new Function('require','exports','process',ts.transpileModule(readFileSync(source,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText)(name=>{if(!(name in modules))throw Error(`unexpected import ${name}`);return modules[name]},exports,{env});return exports}
test('authenticated monthly finalization atomically saves nine signed adoptions and repeat needs no new adoption',async()=>{
 let csv='id,discovered_at,source_type,source_url,topic,title_candidate,category,target_keyword,patient_intent,priority,medical_risk,status,publish_date,notes\n',writes=0,authenticated=0;const topics=Array.from({length:9},(_,i)=>({id:`2026-09-topic-${String(i+1).padStart(3,'0')}`,status:'selected',title:`Synthetic ${i}`,category:'その他',medicalRisk:'low'}))
 const modules={'fs':{},'path':{},'next/cache':{revalidatePath(){}},'@/lib/adminAuth':{requireAdmin:async()=>{authenticated++}},'@/lib/monthlyTopicCandidates':{getTopicCandidatePath:()=> 'data/topic-candidates/synthetic.json'},'@/lib/tieredPublication.mjs':{issueTopicAdoption:row=>tiered.issueTopicAdoption(row,secret)},'@/lib/githubContents':{readGitHubBranchHead:async()=> 'a'.repeat(40),readGitHubFile:async path=>({content:path.includes('claims')?JSON.stringify(tiered.signBlogEvidence('mwf-server-claim',{comparisonEntries:recorded},secret)):path.includes('article-topics')?csv:JSON.stringify({month:'2026-09',targetPostCount:9,topics})}),commitGitHubFiles:async(_message,files,options)=>{writes++;assert.equal(options.expectedHeadSha,'a'.repeat(40));assert.equal(authenticated,1);assert.equal(files.length,10);csv=files[0].content;for(const row of parseCsv(csv)){const proof=tiered.verifyBlogEvidence(JSON.parse(files.find(f=>f.path===`data/topic-adoptions/${row.id}.json`).content),'teacher-topic-adoption',secret);assert.equal(proof.topicVersion,tiered.topicContentVersion(row));assert.equal(proof.topicId,row.id)}return{sha:'b'.repeat(40)}}}}
 const actions=load('src/app/admin/topic-candidates/actions.ts',modules,{GITHUB_REVIEW_TOKEN:'synthetic'})
 assert.equal((await actions.finalizeSelectedTopicCandidatesAction('2026-09')).ok,true)
 assert.equal((await actions.finalizeSelectedTopicCandidatesAction('2026-09')).ok,true);assert.equal(writes,1);assert.equal(authenticated,2)
})
function runtime(){
 const entries=Array.from({length:54},(_,i)=>({path:`content/posts/2026-08-01-synthetic-${i}.md`,source:i<8?'local':'canonical',gitBlob:String(i%10).repeat(40),blob:String(i%10).repeat(64),quarantine:i<4,metadata:{title:`Synthetic ${i}`,excerpt:'Synthetic excerpt',category:'その他'}}));const bytes=Buffer.from(JSON.stringify({payload:{schema:2,entries,quarantine:entries.slice(0,4).map(e=>e.path),preservationHash:'a'.repeat(64),reconciliationHash:'b'.repeat(64)}}));let captured,bodyReads=0,unknown=false,recorded=[]
 const topic={id:'synthetic',title_candidate:'New synthetic',status:'approved'}
 const modules={'./mwfArticleSerialization.mjs':{},'node:fs/promises':{},'node:path':{},'gray-matter':{},'./githubContents':{readGitHubFile:async path=>({content:path.includes('claims')?JSON.stringify(tiered.signBlogEvidence('mwf-server-claim',{comparisonEntries:recorded},secret)):path.includes('article-topics')?'id,title_candidate,status\nsynthetic,New synthetic,approved\n':JSON.stringify(tiered.issueTopicAdoption(topic,secret))}),readGitHubBytes:async path=>{if(path.startsWith('data/mwf/inventories/'))return{bytes};bodyReads++;throw Error('body read forbidden')},readGitHubDirectory:async path=>path==='content/posts'?[...entries.filter(e=>e.source==='canonical').map(e=>({type:'file',path:e.path,sha:recorded.find(r=>r.path===e.path)?.gitBlob??e.gitBlob})),...(unknown?[{type:'file',path:'content/posts/2026-08-01-unknown.md',sha:'f'.repeat(40)}]:[])]:recorded.length?[{type:'file',path:`data/mwf/claims/${'a'.repeat(64)}.json`}]:[]},'./mwfServerAuthority.mjs':{...authority,MWF_INVENTORY_ANCHOR:authority.serverHash(bytes),createServerAuthority:options=>{captured=options;return{}}},'./tieredPublication.mjs':tiered,'./dmpArticleState.mjs':{},'./posts':{},'../../scripts/csv-parser.mjs':{parseCsv},'../../scripts/lib/mwf-inventory.mjs':inventory,'./mwfMinorAuthority.mjs':{},'../../scripts/lib/mwf-tiered-review.mjs':{}}
 load('src/lib/mwfServerRuntime.ts',modules,{ADMIN_REVIEW_COOKIE_SECRET:secret,GITHUB_REVIEW_TOKEN:'synthetic'}).createMwfServerRuntime()
 return{validate:()=>captured.validate({operation:'prepare',topicId:topic.id,topicVersion:tiered.topicContentVersion(topic),artifactPath:null},'a'.repeat(40)),bodyReads:()=>bodyReads,record:(kind)=>{const path=entries[10].path,raw='---\ntitle: Updated synthetic\nexcerpt: Updated synthetic excerpt\ncategory: その他\n---\nSynthetic body';recorded=captured.recordArtifacts({artifactPath:path},{ok:true,kind,...(kind==='normal'?{validatedBytes:Buffer.from(raw)}:{})},kind==='minor'?[{path,content:raw}]:[]);assert.equal(recorded.length,1)},setUnknown:()=>{unknown=true}}
}
test('server compares anchored and listing metadata without historical body reads, unknown changes fail closed',async()=>{const f=runtime();assert.equal((await f.validate()).ok,true);assert.equal(f.bodyReads(),0);f.setUnknown();assert.equal((await f.validate()).ok,false);assert.equal(f.bodyReads(),0)})

test('signed metadata for exact normal draft and minor revision permits subsequent preparation without body reads',async()=>{for(const kind of ['normal','minor']){const f=runtime();f.record(kind);assert.equal((await f.validate()).ok,true);assert.equal(f.bodyReads(),0)}})
